# Generated by Django 2.1 on 2021-01-29 08:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('image1', models.CharField(max_length=255)),
                ('image2', models.CharField(max_length=255)),
                ('image3', models.CharField(max_length=255)),
                ('image4', models.CharField(max_length=255)),
                ('image5', models.CharField(max_length=255)),
                ('image6', models.CharField(max_length=255)),
                ('image7', models.CharField(max_length=255)),
                ('image8', models.CharField(max_length=255)),
                ('postedDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ListingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listingType', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propertyType', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Suburb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listing.Province')),
            ],
        ),
        migrations.AddField(
            model_name='suburb',
            name='town',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listing.Town'),
        ),
        migrations.AddField(
            model_name='listing',
            name='listingType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listing.ListingType'),
        ),
        migrations.AddField(
            model_name='listing',
            name='propertyType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listing.PropertyType'),
        ),
        migrations.AddField(
            model_name='listing',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listing.Province'),
        ),
        migrations.AddField(
            model_name='listing',
            name='suburb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listing.Suburb'),
        ),
        migrations.AddField(
            model_name='listing',
            name='town',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listing.Town'),
        ),
    ]
