# Generated by Django 2.1.7 on 2021-01-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='numberOfBathrooms',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='numberOfBedrooms',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
