# Generated by Django 2.1.7 on 2021-01-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_auto_20210129_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='isAvailable',
            field=models.BooleanField(default=True),
        ),
    ]
