# Generated by Django 2.1.7 on 2021-01-29 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_listing_isavailable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='isAvailable',
            new_name='is_Available',
        ),
    ]
